"use client";

import React from "react";
import { Sparkles, Link2, Unlink } from "lucide-react";
import clsx from "clsx";

/**
 * AI Summary block (Track A2 incident story engine).
 *
 * Default: the grounded facility summary, visually attached to the incident
 * story below it (shared card edge + "attached to timeline" affordance).
 * When `detachable` is set, a small control lets the operator collapse the
 * narrative to a one-line chip so the timeline itself gets the spotlight —
 * useful while presenting replay.
 */
export default function AiSummaryBlock({
  text,
  provider,
  className,
}: {
  text: string;
  /** "openrouter" when LLM-generated, "template" for the deterministic fallback. */
  provider?: string;
  className?: string;
}) {
  const [expanded, setExpanded] = React.useState(true);

  return (
    <section
      className={clsx(
        "rounded-r-lg border-l-[3px] border-accent-violet bg-white/[0.025] p-4",
        className,
      )}
    >
      <div className="flex items-center gap-1.5">
        <Sparkles size={13} className="text-accent-violet" aria-hidden />
        <span className="font-body text-[11px] font-semibold uppercase tracking-widest text-accent-violet">
          AI Summary
        </span>
        {provider && (
          <span
            className="rounded-full bg-bg-surface px-1.5 py-0.5 font-mono text-[9px] text-text-tertiary"
            title={
              provider === "template"
                ? "Deterministic summary built from computed facts (no AI provider configured, or provider unavailable)"
                : `Generated by ${provider}, grounded against computed facts`
            }
          >
            {provider === "template" ? "grounded template" : "grounded GenAI"}
          </span>
        )}
        <button
          type="button"
          onClick={() => setExpanded((v) => !v)}
          aria-expanded={expanded}
          aria-label={expanded ? "Collapse AI summary" : "Expand AI summary"}
          className="ml-auto flex h-5 w-5 items-center justify-center rounded text-text-tertiary transition-colors duration-150 hover:text-text-primary"
        >
          {expanded ? <Unlink size={11} /> : <Link2 size={11} />}
        </button>
      </div>
      {expanded ? (
        <p className="mt-2 font-body text-sm leading-[22px] text-text-primary">{text}</p>
      ) : (
        <p className="mt-1.5 truncate font-body text-xs text-text-secondary">{text}</p>
      )}
    </section>
  );
}
